# config.yml
authentication:
  allow_anonymous_access: True
  single_user_api_key: secret

allow_origins:
  - https://chart-studio.plotly.com
  - http://localhost:3000
  - http://localhost:8080
  - http://localhost:8000

trees:
- tree: databroker.mongo_normalized:Tree.from_uri
  path: /
  args:
    uri: mongodb://admin:huilingpw@bluesky-mongodb:27017/bluesky?authSource=admin
    asset_registry_uri: mongodb://admin:huilingpw@bluesky-mongodb:27017/bluesky?authSource=admin



