FROM debian:bullseye
RUN apt update
RUN apt install git -y
RUN apt install librdkafka-dev -y
RUN apt install python3-pip -y
RUN python3 -c "import distutils.spawn; print(distutils.spawn.find_executable('uvicorn'))"
RUN python3 -m pip install git+https://github.com/bluesky/bluesky-httpserver
COPY ./requirements.txt /requirements.txt
RUN python3 -m pip install -r requirements.txt


COPY ./config.yml ./config.yml
COPY ./start.sh ./start.sh
CMD ["./start.sh"]
