# config.yml
authentication:
  allow_anonymous_access: true
trees:
- tree: databroker.mongo_normalized:Tree.from_uri
  path: /
  args:
    uri: mongodb://admin:huilingpw@localhost:27017/bluesky?authSource=admin
    asset_registry_uri: mongodb://admin:huilingpw@localhost:27017/bluesky?authSource=admin

