FROM debian:bullseye

# python
RUN apt update
RUN apt install git -y
RUN apt install librdkafka-dev -y
RUN apt install python3-pip -y
RUN apt install wget -y
RUN apt install curl -y
RUN apt install nano -y
RUN python3 -m pip install --upgrade --pre databroker[all]
RUN python3 -m pip install --upgrade bluesky ophyd  matplotlib pyqt5 ipython pyepics tiled anyio httpx 
RUN python3 -m pip install --upgrade bluesky-queueserver-api


COPY ./databroker-config.yml /usr/local/share/tiled/CATALOG-BLUESKY.yml
COPY ./databroker-config.yml /etc/tiled/profiles/CATALOG-BLUESKY.yml
COPY ./00-start.py ./00-start.py
COPY ./existing_plans_and_devices.yaml ./existing_plans_and_devices.yaml
COPY ./start_re.sh ./start_re.sh
COPY ./user_group_permissions.yaml ./user_group_permissions.yaml
COPY ./requirements.txt ./requirements.txt
RUN python3 -m pip install -r ./requirements.txt


#RUN qserver-list-plans-devices  --startup-script /usr/local/share/00-start.py
# start
CMD ["./start_re.sh"]
